# Generated by Django 4.2.6 on 2023-11-07 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('pais_de_origem', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='Cadastros',
            new_name='Cadastro',
        ),
        migrations.RemoveField(
            model_name='musicas',
            name='banda',
        ),
        migrations.RemoveField(
            model_name='musicas',
            name='genero',
        ),
        migrations.AddField(
            model_name='genero',
            name='nome',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='biagrafia',
            name='historia',
            field=models.CharField(max_length=2000),
        ),
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('letra_da_musica', models.CharField(max_length=2000)),
                ('ano_de_lancamento', models.CharField(max_length=50)),
                ('banda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.banda')),
                ('compositor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compositor', to='app.pessoa')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.genero')),
                ('interprete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interprete', to='app.pessoa')),
            ],
        ),
        migrations.AlterField(
            model_name='album',
            name='banda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.banda'),
        ),
        migrations.AlterField(
            model_name='album',
            name='musica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.musica'),
        ),
        migrations.AlterField(
            model_name='biagrafia',
            name='banda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.banda'),
        ),
        migrations.DeleteModel(
            name='Bandas',
        ),
        migrations.DeleteModel(
            name='Musicas',
        ),
    ]
