# Generated by Django 4.2.6 on 2023-11-14 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_album_musica_musica_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musica',
            name='banda',
        ),
    ]
