# Generated by Django 4.2.6 on 2023-11-28 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_musica_banda'),
    ]

    operations = [
        migrations.CreateModel(
            name='apresentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('interprete', models.CharField(max_length=2000)),
                ('data_de_apresentacao', models.DateField()),
                ('nome_da_musica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.musica')),
            ],
        ),
    ]
